import java.util.*;

public class Countries
{
    ArrayList<Country> Countries = new ArrayList<>();
    ArrayList<Country> NorthAmerica = newArrayList<>();
    ArrayList<Country> SouthAmerica = newArrayList<>();
    ArrayList<Country> Europe = newArrayList<>();
    ArrayList<Country> Africa = newArrayList<>();
    ArrayList<Country> Asia = newArrayList<>();
    ArrayList<Country> Australia = newArrayList<>();
    
    Country Alaska = new Country("Alaska", "North America", 1);
    Country Alberta = new Country("Alberta", "North America", 1);
    Country CentralAmerica = new Country("Central America", "North America", 1);
    Country EasternUnitedStates = new Country("Eastern United States", "North America", 3);
    Country Greenland = new Country("Greenland", "North America", 1);
    Country NorthwestTerritory = new Country("Northwest Territory", "North America", 1);
    Country Ontario = new Country("Ontario", "North America", 2);
    Country Quebec = new Country("Quebec", "North America", 2);
    Country WesternUnitedStates = new Country("Western United States", "North America", 3);
    Country Argentina = new Country("Argentina", "South America", 1);
    Country Brazil = new Country("Brazil", "South America", 2);
    Country Peru = new Country("Peru", "South America", 1);
    Country Venezuela = new Country("Venezuela", "South America", 1);
    Country GreatBritain = new Country("Great Britain", "Europe", 2);
    Country Iceland = new Country("Iceland", "Europe", 1);
    Country NorthernEurope = new Country("Northern Europe", "Europe", 3);
    Country Scandanavia = new Country("Scandinavia", "Europe", 2);
    Country SouthernEurope = new Country("Southern Europe", "Europe", 3);
    Country Ukraine = new Country("Ukraine", "Europe", 1);
    Country WesternEurope = new Country("Western Europe", "Europe", 3);
    Country Congo = new Country("Congo", "Africa", 1);
    Country EastAfrica = new Country("East Africa", "Africa", 2);
    Country Egypt = new Country("Egypt", "Africa", 1);
    Country Madagascar = new Country("Madagascar", "Africa", 1);
    Country NorthAfrica = new Country("North Africa", "Africa", 2);
    Country SouthAfrica = new Country("South Africa", "Africa", 2);
    Country Afghanistan = new Country("Afghanistan", "Asia", 1);
    Country China = new Country("China", "Asia", 3);
    Country India = new Country("India", "Asia", 3);
    Country Irkutsk = new Country("Irkutsk", "Asia", 1);
    Country Japan = new Country("Japan", "Asia", 2);
    Country Kamchatka = new Country("Kamchatka", "Asia", 1);
    Country MiddleEast = new Country("Middle East", "Asia", 3);
    Country Mongolia = new Country("Mongolia", "Asia", 1);
    Country Siam = new Country("Siam", "Asia", 2);
    Country Siberia = new Country("Siberia", "Asia", 1);
    Country Ural = new Country("Ural", "Asia", 1);
    Country Yakutsk = new Country("Yakutsk", "Asia", 1);
    Country EasternAustralia = new Country("Eastern Australia", "Australia", 3);
    Country Indonesia = new Country("Indonesia", "Australia", 2);
    Country NewGuinea = new Country("New Guinea", "Australia", 1);
    Country WesternAustralia = new Country("Western Australia", "Australia", 2);

    public void CountryAdd()
    {
        Countries.add(Alaska);
        Countries.add(Alberta);
        Countries.add(CentralAmerica);
        Countries.add(EasternUnitedStates);
        Countries.add(Greenland);
        Countries.add(NorthwestTerritory);
        Countries.add(Ontario);
        Countries.add(Quebec);
        Countries.add(WesternUnitedStates);
        Countries.add(Argentina);
        Countries.add(Brazil);
        Countries.add(Peru);
        Countries.add(Venezuela);
        Countries.add(GreatBritain);
        Countries.add(Iceland);
        Countries.add(NorthernEurope);
        Countries.add(Scandanavia);
        Countries.add(SouthernEurope);
        Countries.add(Ukraine);
        Countries.add(WesternEurope);
        Countries.add(Congo);
        Countries.add(EastAfrica);
        Countries.add(Egypt);
        Countries.add(Madagascar);
        Countries.add(NorthAfrica);
        Countries.add(SouthAfrica);
        Countries.add(Afghanistan);
        Countries.add(China);
        Countries.add(India);
        Countries.add(Irkutsk);
        Countries.add(Japan);
        Countries.add(Kamchatka);
        Countries.add(MiddleEast);
        Countries.add(Mongolia);
        Countries.add(Siam);
        Countries.add(Siberia);
        Countries.add(Ural);
        Countries.add(Yakutsk);
        Countries.add(EasternAustralia);
        Countries.add(Indonesia);
        Countries.add(NewGuinea);
        Countries.add(WesternAustralia);
        Countries.add(Alaska);
        Countries.add(Alberta);
        Countries.add(CentralAmerica);
        Countries.add(EasternUnitedStates);
        Countries.add(Greenland);
        Countries.add(NorthwestTerritory);
        Countries.add(Ontario);
        Countries.add(Quebec);
        Countries.add(WesternUnitedStates);
        Countries.add(Argentina);
        Countries.add(Brazil);
        Countries.add(Peru);
        Countries.add(Venezuela);
        Countries.add(GreatBritain);
        Countries.add(Iceland);
        Countries.add(NorthernEurope);
        Countries.add(Scandanavia);
        Countries.add(SouthernEurope);
        Countries.add(Ukraine);
        Countries.add(WesternEurope);
        Countries.add(Congo);
        Countries.add(EastAfrica);
        Countries.add(Egypt);
        Countries.add(Madagascar);
        Countries.add(NorthAfrica);
        Countries.add(SouthAfrica);
        Countries.add(Afghanistan);
        Countries.add(China);
        Countries.add(India);
        Countries.add(Irkutsk);
        Countries.add(Japan);
        Countries.add(Kamchatka);
        Countries.add(MiddleEast);
        Countries.add(Mongolia);
        Countries.add(Siam);
        Countries.add(Siberia);
        Countries.add(Ural);
        Countries.add(Yakutsk);
        Countries.add(EasternAustralia);
        Countries.add(Indonesia);
        Countries.add(NewGuinea);
        Countries.add(WesternAustralia);Countries.add(Alaska);
        Countries.add(Alberta);
        Countries.add(CentralAmerica);
        Countries.add(EasternUnitedStates);
        Countries.add(Greenland);
        Countries.add(NorthwestTerritory);
        Countries.add(Ontario);
        Countries.add(Quebec);
        Countries.add(WesternUnitedStates);
        Countries.add(Argentina);
        Countries.add(Brazil);
        Countries.add(Peru);
        Countries.add(Venezuela);
        Countries.add(GreatBritain);
        Countries.add(Iceland);
        Countries.add(NorthernEurope);
        Countries.add(Scandanavia);
        Countries.add(SouthernEurope);
        Countries.add(Ukraine);
        Countries.add(WesternEurope);
        Countries.add(Congo);
        Countries.add(EastAfrica);
        Countries.add(Egypt);
        Countries.add(Madagascar);
        Countries.add(NorthAfrica);
        Countries.add(SouthAfrica);
        Countries.add(Afghanistan);
        Countries.add(China);
        Countries.add(India);
        Countries.add(Irkutsk);
        Countries.add(Japan);
        Countries.add(Kamchatka);
        Countries.add(MiddleEast);
        Countries.add(Mongolia);
        Countries.add(Siam);
        Countries.add(Siberia);
        Countries.add(Ural);
        Countries.add(Yakutsk);
        Countries.add(EasternAustralia);
        Countries.add(Indonesia);
        Countries.add(NewGuinea);
        Countries.add(WesternAustralia);
    }
}
